### ISSUE TITLE
4to Registrar los resultados de cada enfrentamiento para determinar los ganadores de dicho enfrentamiento.

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#18]
Tienen:

- Una lista de emparejamientos
- El objeto del Torneo
- Display gráfico de las llaves

Tienen que hacer

- Form registro de resultados
- Registro de quién avanza en DB
- Actualización en llaves

**Comment by dianamongar** [comment]
debemos añadir una pantalla de ganador del torneo?
