### ISSUE TITLE
1ro Registrar como participante a un torneo mediante un código único de un torneo

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#21]
tienes:

- el sistema como está ahora

TODO:

- Simular o de kahoot para registrarse
- Pantalla como admin para ver usaurio registrados

**Comment by CamperoJose** [comment]
- boton para ir a formulario:
<img width="1235" alt="Captura de pantalla 2024-11-17 a la(s) 8 43 37 p  m" src="https://github.com/user-attachments/assets/9271c169-c553-4093-8a39-af8d7177c065">
- formulario para registrarse como participante:
<img width="1343" alt="Captura de pantalla 2024-11-17 a la(s) 8 43 27 p  m" src="https://github.com/user-attachments/assets/7536a76d-b037-425c-ba15-9592fc03d8c4">
- ver lista de participantes como participante:
<img width="1346" alt="Captura de pantalla 2024-11-17 a la(s) 8 43 19 p  m" src="https://github.com/user-attachments/assets/c2e1b1e0-6df6-454c-8efa-fe2dbd0c734f">
-ver lista de partcipantes como administrador:
<img width="540" alt="Captura de pantalla 2024-11-17 a la(s) 8 43 45 p  m" src="https://github.com/user-attachments/assets/68c67def-1e00-4ede-af6f-5df8ae182519">
<img width="1345" alt="Captura de pantalla 2024-11-17 a la(s) 8 44 01 p  m" src="https://github.com/user-attachments/assets/85087f72-8e2d-4ed6-a864-1ec5d030e748">
