### ISSUE TITLE
BUG Limitación de accesos

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#36]
Son dos errores: 

- Es posible que un participante/expectador modifique los resultados de un bracket. Solo el propietario de un torneo debería poder modificar estos valores.
- Es posible acceder directamente a los urls de admin de un torneo desde la barra de búsqueda

**Comment by CamperoJose** [comment]
<img width="1339" alt="Captura de pantalla 2024-12-06 a la(s) 8 57 17 p  m" src="https://github.com/user-attachments/assets/628f3dfb-6a47-4259-97da-5f3adaf39349">

## Casos de acceso a la ruta `tournament-details/[tournament-code]`

A continuación, se describe el flujo para acceder a un torneo en la ruta `tournament-details/[tournament-code]`:

| **Caso**                                                                 | **Acción**                                                        |
|--------------------------------------------------------------------------|------------------------------------------------------------------|
| **Caso 1: Accedo a un torneo mío**                                       | Se muestra el torneo sin problemas.                              |
| **Caso 2: Accedo a un torneo sin estar autenticado**                     | El usuario es redirigido a la página `/login`.                   |
| **Caso 3: Accedo a un torneo que no es mío o con un email diferente**    | Se muestra un mensaje indicando que no se puede acceder al torneo. |

**Comment by CamperoJose** [comment]
Tengo pendiente corregir el error que permite que solo el dueño de un torneo pueda agregar los resultados de un enfrentamiento en la ruta /bracket-tournament. Esta funcionalidad se completará cuando se implemente la opción de mostrar al ganador después de registrar el último enfrentamiento. Para solucionar este problema, crearé dos pantallas diferenciadas: una para los espectadores y otra para los administradores.

**Comment by OscarCampohermoso** [comment]
Ya pude agregar la funcionalidad donde solo dueño de un torneo puede agregar resultados:
<img width="1109" alt="Captura de pantalla 2024-12-10 a la(s) 16 23 57" src="https://github.com/user-attachments/assets/5029d030-6a68-4e08-a0de-604515273758">

<img width="1123" alt="Captura de pantalla 2024-12-10 a la(s) 16 25 09" src="https://github.com/user-attachments/assets/be0e45a9-553b-4d22-a2fc-613cce0c65b6">
