### ISSUE TITLE
HU Gestión de Torneos

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#37]
![image](https://github.com/user-attachments/assets/c6b7ea55-bf08-40c4-9b47-36703bf64d5e)

Dentro de esta vista:

1. Separar entre torneos próximos/en curso/finalizados
2. Mostrar tags en tabla, añadir búsqueda por tabla
3. En torneos finalizados todavía guardar la opción de ver resultados
4. En torneos en curso cambiar iniciar->ver

**Comment by OscarCampohermoso** [comment]
Los estados se actualizan automáticamente: al crear un torneo, el estado inicial será "Soon". Al generar los brackets, cambiará a "In Progress". Para finalizar el torneo, únicamente el creador podrá ver un botón en la pantalla de los brackets que le permitirá finalizarlo:

<img width="1016" alt="Captura de pantalla 2024-12-10 a la(s) 16 35 52" src="https://github.com/user-attachments/assets/2407319f-d5dd-4bc5-a67b-d1a0545132b0">
<img width="1005" alt="Captura de pantalla 2024-12-10 a la(s) 16 36 45" src="https://github.com/user-attachments/assets/23a1ce33-1deb-4360-a387-80a5dc508dd6">
