### ISSUE TITLE
HU Estilizar vista de participantes

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#39]
![image](https://github.com/user-attachments/assets/7943481f-01d0-478f-9c77-c1e83dc67ff1)

En esta vista:

1. Hacer más evidente la distinción entre vista de organizador vs. participante (quizá incluyendo los detalles del torneo en alguna? 🤷🏼)
2. Encontrar alguna forma de que los participantes personalicen la imagen (puntos extra si se logra incluir esa imagen a los brackets
3. Validar que la vista de participantes sea mobile-friendly (responsive y con buen UX)

**Comment by CamperoJose** [comment]
<img width="565" alt="Captura de pantalla 2024-12-06 a la(s) 9 44 09 p  m" src="https://github.com/user-attachments/assets/b9df5106-0554-4f6e-b1ef-15b182d71deb">

1. Se actualizó la vista de participantes de administrador agregando mayor información del torneo, además se verifico que sea responsive.

**Comment by CamperoJose** [comment]
2. Se agregaron Iconos que los participantes pueden escoger al unirse a un torneo:

- Formulario de registro:
<img width="1197" alt="Captura de pantalla 2024-12-07 a la(s) 7 17 20 p  m" src="https://github.com/user-attachments/assets/2b246490-e0b3-4dbc-b4f1-a3761cc35fbe">

- Vista de Participantes como espectador:
<img width="1261" alt="Captura de pantalla 2024-12-07 a la(s) 7 14 42 p  m" src="https://github.com/user-attachments/assets/9136b2a5-e0aa-477d-a0aa-06efd0005855">

- Vista de participantes como administrador:
<img width="594" alt="Captura de pantalla 2024-12-07 a la(s) 7 19 21 p  m" src="https://github.com/user-attachments/assets/1745a371-9211-40e2-b74b-e4a575633d43">

- No se pudo hacer que se vean los iconos en los brakets creados, pero si se lo agrego al pop up para registrar los resultados de un enfrentamiento:
<img width="1142" alt="Captura de pantalla 2024-12-07 a la(s) 7 16 11 p  m" src="https://github.com/user-attachments/assets/abde3bc3-5afa-446a-b90d-d32bd4a6b9a7">


3. Se verifico que todas estas pantallas son responsive

**Comment by OscarCampohermoso** [comment]
Logre que los monitos se mostraran en el bracket:

<img width="647" alt="Captura de pantalla 2024-12-10 a la(s) 17 39 38" src="https://github.com/user-attachments/assets/9cb46d15-53f9-442f-b2eb-2370ed49bdc2">
