### ISSUE TITLE
Informe de Sprints y funciones dentro del grupo

### ISSUE THREAD

**Issue by CarrascoAlejandro** [CarrascoAlejandro/tournado#40]
Se deben incluir 5 subsecciones al documento:

1. Sprint 1: Este fue el sprint de planificación problablemente no sea muy extenso, revisar el documento
2. Sprint 2: Primera presentación de funcionalidad ver los issues que tienen el label `good first issue` https://github.com/CarrascoAlejandro/tournado/issues?q=is%3Aissue+label%3A%22good+first+issue%22
3. Sprint 3: Segunda presentación de funcionalidad ver los issues que tienen el label `help wanted` https://github.com/CarrascoAlejandro/tournado/issues?q=is:issue+label:%22help+wanted%22+
4. Sprint 4: Esta presentación (final) ver los issues que tienen el label `Final Presentation` https://github.com/CarrascoAlejandro/tournado/issues?q=is:issue+label:%22Final+Presentation%22+
5. Funciones dentro del grupo: Qué hizo cada quién.

**Comment by OscarCampohermoso** [comment]
Diapos: @FabiolaMartinez1 
Documento: @GabGabZiz

**Comment by CarrascoAlejandro** [comment]
https://docs.google.com/document/d/1HZK5owB9SGisVvhhYUAHQrqkU5Tk0isBQxuNoG700q8/edit?tab=t.0
