### ISSUE TITLE
Funcionalidad para que un administrador pueda eliminar participantes antes de hacer los brakets

### ISSUE THREAD

**Issue by CamperoJose** [CarrascoAlejandro/tournado#41]

**Comment by CamperoJose** [comment]
Un administrador ahora puede eliminar a cualquier participante que se unió a un torneo. Si ya se hicieron los brakets no se borrara de las llaves creadas. 

![Grabaciondepantalla2024-12-07alas7 41 27p m -ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/7e76b2ce-4a32-453b-a36b-4677a63857f3)

**Comment by CarrascoAlejandro** [comment]
Good
