### ISSUE TITLE
Crear pantalla para gestionar un torneo en curso

### ISSUE THREAD

**Issue by OscarCampohermoso** [CarrascoAlejandro/tournado#6]
<img width="738" alt="Captura de pantalla 2024-10-15 a la(s) 17 41 55" src="https://github.com/user-attachments/assets/22f40657-ed7f-4695-a942-26c345929c54">

---
HU-004: Registrar los resultados de cada enfrentamiento

Como administrador, quiero registrar los resultados de cada enfrentamiento, para determinar los ganadores de dicho enfrentamiento y actualizar el progreso del torneo.

---
HU-006: Determinar aleatoriamente los emparejamientos

Como administrador, quiero determinar aleatoriamente los emparejamientos entre participantes, para promover competencias justas y equilibradas en el torneo.

---
HU-007: Eliminar o reemplazar a un participante

Como administrador, quiero eliminar o reemplazar a un participante en un torneo en curso, para gestionar su retiro o descalificación y mantener la integridad del torneo.

**Comment by CarrascoAlejandro** [comment]
Completado en la 3ra presentación
