### ISSUE TITLE
Crear pantalla para ver el resultado de un torneo finalizado

### ISSUE THREAD

**Issue by OscarCampohermoso** [CarrascoAlejandro/tournado#7]
<img width="736" alt="Captura de pantalla 2024-10-15 a la(s) 17 45 21" src="https://github.com/user-attachments/assets/60e1d9ea-7a3f-414a-8434-af890e424b3a">
<img width="751" alt="Captura de pantalla 2024-10-15 a la(s) 17 47 27" src="https://github.com/user-attachments/assets/ede83553-a549-4e8a-abba-abf93ee3b1ab">

---
HU-005: Visualizar resultados en un torneo

Como participante o espectador, quiero visualizar los resultados en un torneo, para saber el progreso actual y los próximos enfrentamientos.

---
HU-008: Ver un resumen de los resultados de los participantes

Como participante o espectador, quiero ver un resumen de los resultados de los participantes individualmente, para conocer su desempeño y compararlo con otros competidores.

**Comment by CarrascoAlejandro** [comment]
Close enough
