### ISSUE TITLE
Crear pantalla para unirse a un torneo mediante código

### ISSUE THREAD

**Issue by OscarCampohermoso** [CarrascoAlejandro/tournado#8]
<img width="682" alt="Captura de pantalla 2024-10-15 a la(s) 17 49 23" src="https://github.com/user-attachments/assets/0e38462e-a274-4793-91cf-1e1fd266b163">

---
HU-0013: Registrar como participante en un torneo mediante un código único

Como participante, quiero registrarme en un torneo utilizando un código único, para poder unirme al torneo específico y competir en los enfrentamientos.

**Comment by CarrascoAlejandro** [comment]
Cubierto durante 3ra presentación
